name = "Paperesque"
license = "MIT"
licenselink = "https://github.com/capnfabs/paperesque/blob/mainline/LICENSE.md"
description = "A lightweight theme for personal websites."
homepage = "https://github.com/capnfabs/paperesque/"
tags = ["blog", "personal", "light", "responsive", "minimal"]
features = ["responsive", "margin notes", "resource processing", "draft highlighting"]
min_version = "0.74.3"

[author]
    name = "Fabian Tamp"
    homepage = "https://capnfabs.net"
